# Site settings
title: developer 
email: soi.yoon624@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: develope 

# Social icons
facebook: 
linkedin: 
github: yoonsoi
deviantart: 
codepen: 

footer: © 

# Build settings
markdown: 
